from typing import Annotated, Literal
from dotenv import load_dotenv
from fastapi import WebSocket
from typing_extensions import TypedDict

from langgraph.graph import StateGraph, START, END, MessagesState
from langgraph.graph.message import add_messages
from langchain_openai import AzureChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage

from prompts import ADOPROXYAGENT_PROMPT, ORCHESTRATOR_PROMPT, PIPELINERUNAGENT_PROMPT
from langchain.agents import Tool
from tools import get_repo_pipeline_info, trigger_pipeline
from langgraph.types import interrupt, Interrupt
from langgraph.checkpoint.memory import MemorySaver

load_dotenv()

# --- Configuration ---
deployment_name = "gpt-4o"

class State(TypedDict):
    messages: Annotated[list, add_messages]
    last_speaker: str
    decision: str

class  PipelineRoute(TypedDict):
    step: Literal['ado_proxy_agent','pipeline_run_agent','human','END']

llm = AzureChatOpenAI(
    azure_deployment=deployment_name,
    temperature=0
)

tools = [
    get_repo_pipeline_info,
    trigger_pipeline
]
tools_by_name = {tool.name: tool for tool in tools}

llm_with_tools = llm.bind_tools(tools=tools)
pipeline_router = llm.with_structured_output(PipelineRoute, method="function_calling")

# Nodes
def orchestrator(state: State):
    
    decision = pipeline_router.invoke(
        [
            SystemMessage(content=ORCHESTRATOR_PROMPT)
        ] + state["messages"]
    )

    return {"decision": decision["step"],"messages": state["messages"], "last_speaker": "orchestrator"}

def ADOProxyAgent(state: State):
    
    result = llm_with_tools.invoke(
        [
            SystemMessage(content=ADOPROXYAGENT_PROMPT)
        ] + state["messages"]
    )

    return {"messages": state["messages"] + [result], "last_speaker": "ado_proxy_agent"}

def human_node(state: MessagesState):
    """A node for collecting user input."""
    user_input = interrupt({"messages":"Enter Value.", "last_speaker":"human"})

    # Determine the **active agent** from the state, so 
    # we can route to the correct agent after collecting input.
    # For example, add a field to the state or use the last active agent.
    # or fill in `name` attribute of AI messages generated by the agents.

    return {"messages": state["messages"] + [HumanMessage(content=user_input)], "last_speaker": "human"}


def PipelineRunAgent(state: State):
    result = llm_with_tools.invoke(
        [
            SystemMessage(content=PIPELINERUNAGENT_PROMPT),
        ] + state["messages"]
    )
    
    return {"messages": state["messages"] + [result] , "last_speaker": "pipeline_run_agent"}

def tool_node(state: dict):
    """Performs the tool call"""

    result = []
    for tool_call in state["messages"][-1].tool_calls:
        tool = tools_by_name[tool_call["name"]]
        observation = tool.invoke(tool_call["args"])
        result.append(ToolMessage(content=observation, tool_call_id=tool_call["id"]))
    return {"messages": state["messages"] + result, "last_speaker": "tool_call"}


def tool_continue(state: State) -> Literal["environment", "END"]:
    """Decide if we should continue the loop or stop based upon whether the LLM made a tool call"""

    messages = state["messages"]
    last_message = messages[-1]
    # If the LLM makes a tool call, then perform an action
    if hasattr(last_message,"tool_calls") and len(last_message.tool_calls) > 0:
        return "Action"
    # Otherwise, we stop (reply to the user)
    return END


# Build workflow
graph = StateGraph(State)

# Add nodes
graph.add_node("ado_proxy_agent", ADOProxyAgent)
graph.add_node("pipeline_run_agent", PipelineRunAgent)
graph.add_node("ado_proxy_agent_tool_node", tool_node)
graph.add_node("pipeline_run_agent_tool_node", tool_node)
graph.add_node("human", human_node)
graph.add_node("orchestrator", orchestrator)

# Add edges to connect nodes
graph.add_edge(START, "orchestrator")

graph.add_conditional_edges(
    "orchestrator",
    lambda route: route["decision"],
    {  
        "ado_proxy_agent": "ado_proxy_agent",
        "pipeline_run_agent": "pipeline_run_agent",
        "human": "human",
        "END": END
    },
)

graph.add_conditional_edges(
    "ado_proxy_agent",
    tool_continue,
    {  
        "Action": "ado_proxy_agent_tool_node",
        END: "orchestrator"
    },
)

graph.add_conditional_edges(
    "pipeline_run_agent",
    tool_continue,
    {  
        "Action": "pipeline_run_agent_tool_node",
        END: "orchestrator"
    },
)

graph.add_edge("human","orchestrator")

graph.add_edge("ado_proxy_agent_tool_node","ado_proxy_agent")
graph.add_edge("pipeline_run_agent_tool_node","pipeline_run_agent")

# Compile workflow
checkpointer=MemorySaver()
router_workflow = graph.compile(checkpointer=checkpointer)
thread_config = {"configurable": {"thread_id": "1"}}

# import colorama
# colorama.init()

# def stream_graph_updates(user_input: str):
#     for event in router_workflow.stream(input={"messages": [{"role": "user", "content": user_input}], "last_speaker": "User"}, config=thread_config):
#         for value in event.values():
#             # print(value)
#             if isinstance(value, tuple) and isinstance(value[0], Interrupt):
#                 value = value[0].value
#                 print(f"{colorama.Fore.GREEN} {value['last_speaker']} {colorama.Style.RESET_ALL}: {value['messages']}")
#             else:
#                 print(f"{colorama.Fore.GREEN} {value['last_speaker']} {colorama.Style.RESET_ALL}: {value['messages'][-1]}")

# while True:
#     try:
#         # if initial_state["messages"]:
#         #     print(f"Previous messages: {initial_state['messages']}")

#         #initial_state = {"messages": [], "last_speaker": "User", "decision": "Start"}
#         # Get user input from the prompt
#         user_input = input("User: ")
#         if user_input.lower() in ["quit", "exit", "q"]:
#             print("Goodbye!")
#             break

#         stream_graph_updates(user_input)
#         #initial_state = {"messages": initial_state["messages"] + [HumanMessage(content=user_input)], "last_speaker": "User"}


#     except Exception as e:
#         print(f"An error occurred: {e}")
#         break